trigger:
- master

pool:
  name: 'Default'

steps:
- task: FortifyScan@4
  inputs:
    appname: 'Smart Locker'
    appversion: 1.0
    useCloudscan: true
    overrideMsBuild: true
    buildCommand: 'sourceanalyzer -b $(Build.BuildID) $env:Build_SourcesDirectory '
    
    

    
